name: API Specs Workflow

on:
  workflow_dispatch:

jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Types Tasks
        run: |
          echo "Running types tasks..."
