name: Backend Workflow

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Backend Tests
        run: |
          echo "Running backend tests..."
          echo 90
          if [ "${{ secrets.TEST_SECRET }}" == "OK" ]; then
            echo "Test secret is found And its value is [${{ secrets.TEST_SECRET }}]"
          else
            echo "Test secret is NOT found"
          fi
