name: Backend Workflow

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Backend Tests
        run: |
          echo "Running backend tests..."
          echo 90
