name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  trigger_types: "false"
  trigger_api_specs: "false"
  trigger_utils: "false"
  trigger_backend: "false"
  trigger_frontend: "false"

jobs:
  trigger-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Check if types files changed
        id: check_types_changes
        run: |
          # Get the list of files changed in the last commit
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Check if any changed file is inside the 'types' directory
          if echo "$changed_files" | grep -q '^types/'; then
            echo "Types files changed"
            echo "trigger_types=true" >> $GITHUB_ENV
          else
            echo "No changes in the types directory"
            echo "trigger_types=false" >> $GITHUB_ENV
          fi

      - name: Trigger Types Workflow
        if: env.trigger_types == 'true'
        uses: ./.github/workflows/types.yml

  trigger-api-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Check if API specs files changed
        id: check_api_specs_changes
        run: |
          # Get the list of files changed in the last commit
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Check if any changed file is inside the 'api-specs' directory
          if echo "$changed_files" | grep -q '^api-specs/'; then
            echo "API specs files changed"
            echo "trigger_api_specs=true" >> $GITHUB_ENV
          else
            echo "No changes in the API specs directory"
            echo "trigger_api_specs=false" >> $GITHUB_ENV
          fi

      - name: Trigger API Specs Workflow
        if: env.trigger_api_specs == 'true'
        uses: ./.github/workflows/api-specs.yml

  trigger-utils:
    runs-on: ubuntu-latest
    needs:
      - trigger-types

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Check if utils files changed
        id: check_utils_changes
        run: |
          # Get the list of files changed in the last commit
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Check if any changed file is inside the 'utils' directory
          if echo "$changed_files" | grep -q '^utils/'; then
            echo "Utils files changed"
            echo "trigger_utils=true" >> $GITHUB_ENV
          else
            echo "No changes in the utils directory"
            echo "trigger_utils=false" >> $GITHUB_ENV
          fi

      - name: Trigger Utils Workflow
        if: env.trigger_utils == 'true'
        uses: ./.github/workflows/utils.yml

  trigger-backend:
    runs-on: ubuntu-latest
    needs:
      - trigger-api-specs
      - trigger-utils

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Check if backend files changed
        id: check_backend_changes
        run: |
          # Get the list of files changed in the last commit
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Check if any changed file is inside the 'backend' directory
          if echo "$changed_files" | grep -q '^backend/'; then
            echo "Backend files changed"
            echo "trigger_backend=true" >> $GITHUB_ENV
          else
            echo "No changes in the backend directory"
            echo "trigger_backend=false" >> $GITHUB_ENV
          fi

      - name: Trigger Backend Workflow
        if: env.trigger_backend == 'true'
        uses: ./.github/workflows/backend.yml

  trigger-frontend:
    runs-on: ubuntu-latest
    needs:
      - trigger-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Check if frontend files changed
        id: check_frontend_changes
        run: |
          # Get the list of files changed in the last commit
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Check if any changed file is inside the 'frontend' directory
          if echo "$changed_files" | grep -q '^frontend/'; then
            echo "Frontend files changed"
            echo "trigger_frontend=true" >> $GITHUB_ENV
          else
            echo "No changes in the frontend directory"
            echo "trigger_frontend=false" >> $GITHUB_ENV
          fi

      - name: Trigger Frontend Workflow
        if: env.trigger_frontend == 'true'
        uses: ./.github/workflows/frontend.yml
